### ISSUE TITLE
Incorrect bit in build

### ISSUE THREAD

**Issue by nateonline** [Jonas-Hack/Unity-Thrustmaster-T16KM-HOSAS-InputSystem#2]
This works great in Editor, but for some reason these scripts don't work when I run them in a build.

I've created a development build with the following settings:
![image](https://github.com/Jonas-Hack/Unity-Thrustmaster-T16KM-HOSAS-InputSystem/assets/38987385/7614c9b8-ca39-4e52-8940-145b5383962c)

Here's some additional settings I have set for reference:
Scripting Backend = `Mono`
Api Compatibility Level = `.NET Framework`

When I attach my debugger to the build and breakpoint on `SetStickStatus()`, I'm never getting an `isRight` joystick come through, even though I am on the build.
![image](https://github.com/Jonas-Hack/Unity-Thrustmaster-T16KM-HOSAS-InputSystem/assets/38987385/c4007ad3-8d06-4e61-bfe6-1f8034a60a4f)

In a build, the `state.leftRightSwitch` is `8` for both joysticks, regardless of the switch on the bottom. Thus both count as left. I also tried unplugging and re-plugging them at runtime, and the breakpoint was always hit, but never giving a right joystick.

My hunch is that the bit that needs to be read is in a different position in editor vs build. But I don't know enough about this to get the entire list of bits and compare them.

Either way, thanks for a great package. It'll be exactly what we need if I can get this working in a build. 
Let me know if you have any questions!

**Comment by Jonas-Hack** [comment]
Hi, thank you for another bug report :)

I'm having a little trouble reproducing your exact issue - though there definitely is one.
Since the issue seems to manifest differently on my machine, there are a few things I'm asking you to try out:


1. Does wiggling both sticks a few seconds after startup do anything?

2. If you hold the hat switch (d-pad), is the ``state.leftRightSwitch`` still 8?

3. If you pull the flight sticks out of their USB sockets and then plug them back in, while the game is running, does that fix it?

4. If you flip the all important switch, does anything change?

5. If you set breakpoints, at the lambdas of ``changeHandAction`` (line 60ff, though your IDE seems to count differently), when are they reached?


From what I can tell so far, it looks like the ``changeHandAction`` not being triggered correctly - in the runtime only. This might have something to do with the difference of the ``InitializeOnLoadMethod``. In my tests the correct side was always detected correctly - as long as the detection itself was actually triggered, which is apparently not guaranteed.

Thank you for reaching out! I'll look further into this soon

**Comment by nateonline** [comment]
Well... After testing this a few days later, it seems to nit be an issue 😑 Maybe I was doing something weird like not debugging with the exact same code as was in the build, etc. I'll keep an eye on it. Thanks for your help!

**Comment by Jonas-Hack** [comment]
Well, from my current testing, you were not completely wrong. There is an issue with sticks not being assigned a side on startup.

This problem then immediately fixes itself, once both sticks are being used - which is why I did not previously notice the problem.

For now the existing script works good enough. But don't hesitate to reach out, if there are any further problems.

I'm happy to help :)
